spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/entry}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:qpwoeiru1768}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  profiles:
    include: oauth

jwt:
  secretKey: ${JWT_SECRET_KEY:asdjfkasdhfjkashdfkashdfkahsdjkfahskdf}
  accessExpiredExp: ${JWT_ACCESS_EXP:1800000}
  refreshExpiredExp: ${JWT_REFRESH_EXP:432000000}
  header: ${JWT_HEADER:Authorization}
  prefix: ${JWT_PREFIX:Bearer}